name: YuCobblemonCard
version: '2.0.3'
main: com.wuyumoom.yucobblemoncard.YuCobblemonCard
api-version: '1.21'
depend: [YuCore ,PlaceholderAPI]
commands:
  ycard:
    aliases: [yucard]
    description: 方可梦卡片系统主命令
    usage: /<command> [子命令]